/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export interface ReportsDates {
  day: number;
  day_of_week: number | null;
  hour: number;
  id: Generated<Int8>;
  is_weekend: boolean | null;
  month: number;
  quarter: number | null;
  year: number;
}

export interface ReportsSeats {
  car_type: string | null;
  class: string;
  id: Generated<Int8>;
  train: string;
}

export interface ReportsStations {
  city: string | null;
  id: Generated<Int8>;
  name: string;
  region: string;
}

export interface ReportsTickets {
  arrive_date: Int8;
  arrive_stn: Int8;
  booking_confirmed: Generated<boolean | null>;
  cost: number;
  depart_date: Int8;
  depart_stn: Int8;
  id: Generated<Int8>;
  seat: Int8;
  /**
   * Original ticket_id from the primary OLTP database for ETL tracking
   */
  source_ticket_id: string | null;
}

export interface DB {
  "reports.dates": ReportsDates;
  "reports.seats": ReportsSeats;
  "reports.stations": ReportsStations;
  "reports.tickets": ReportsTickets;
}
