/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Bookings {
  confirm_status: Generated<boolean>;
  cost_total: number;
  email: string;
  id: Generated<Int8>;
}

export interface Cars {
  car_no: number;
  id: Int8;
  seat_count: number;
  train_id: Int8;
  type: string;
}

export interface Journeys {
  id: Generated<Int8>;
  route: number;
  train_no: Int8;
}

export interface Routes {
  direction: string;
  id: Generated<Int8>;
}

export interface Schedule {
  arrival: Timestamp;
  departure: Timestamp;
  id: Generated<Int8>;
  journey_id: Int8;
  occupancy: Generated<number>;
  station: string;
}

export interface Seat {
  car: Int8;
  column: number;
  id: Generated<Int8>;
  row: number;
}

export interface Station {
  id: Generated<Int8>;
  name: string;
}

export interface Tickets {
  booking_id: Int8;
  class: string;
  cost: number;
  destination: Int8;
  journey: Int8;
  origin: Int8;
  reserved_at: Generated<Timestamp>;
  seat: number;
  ticket_id: Generated<string>;
}

export interface Trains {
  capacity: number;
  id: Generated<Int8>;
}

export interface DB {
  bookings: Bookings;
  cars: Cars;
  journeys: Journeys;
  routes: Routes;
  schedule: Schedule;
  seat: Seat;
  station: Station;
  tickets: Tickets;
  trains: Trains;
}
